#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.
set -x  # All executed commands are printed to the terminal

export DEBIAN_FRONTEND=noninteractive

# Create the user 'mysql' with uid 1000
adduser --uid 1000 --disabled-login --shell=/bin/false --gecos "MySQL Server" --no-create-home --home /nonexistent mysql

# Add Sid repository to install phpMyAdmin
echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list

# Select Apache server by default in phpMyAdmin installation
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections

aptitude update ; aptitude install -y mariadb-server

service mysql start

# Create user 'mysql' with password 'mysql' with all privileges
mysql -u root mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'localhost' IDENTIFIED BY 'mysql' WITH GRANT OPTION;"

# Allow user 'root' to login from outside the console
# mysql -u root mysql -e "update user set plugin='' where user='root'; flush privileges;"

aptitude install -y phpmyadmin
service mysql stop

# Allow login without password in phpMyAdmin
# sed -i "103d" /etc/phpmyadmin/config.inc.php
# sed -i "103i\ \ \ \ \$cfg['Servers'][\$i]['AllowNoPassword'] = TRUE;" /etc/phpmyadmin/config.inc.php

# Bugfix for phpMyAdmin 4.6.6
sed -i 's/\ == 1)/)\ == 1/' /usr/share/phpmyadmin/libraries/sql.lib.php

apt-get -y autoremove ; aptitude -y autoclean ; apt-get -y autoclean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.aptitude
